version: 2.1

orbs:
  # Include orbs here if you need them

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Example image
    steps:
      - checkout
      - run:
          name: Execute Tests
          command: ./run_tests.sh  # Replace with your test script

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
