version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install
      - run: npm install
      - run: npm test
workflows:
  version: 2
  build:
    jobs:
      - build
